FROM python:3.9-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app
ADD . /app/
RUN mkdir -p /app/logs

RUN DEBIAN_FRONTEND=noninteractive apt-get update -y && apt-get install -y nginx libpq5 build-essential python3-dev libpq-dev && \
    pip3 --disable-pip-version-check --no-cache-dir install install circus==0.17.1 uwsgi==2.0.19.1 pipenv==2020.11.15 && \
    apt-get purge -y build-essential python3-dev libpq-dev && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*