apiVersion: v1
kind: Service
metadata:
  name: era5-api
  labels:
    app.kubernetes.io/name: era5-api
spec:
  selector:
    app.kubernetes.io/name: era5-api
  ports:
    - name: http
      port: 5052
      targetPort: http
