apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: era5-data
  namespace: podnebnik  # adapt to your namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  # 18 stations × ~50 MB CSVs + SQLite
