# Generated by Django 3.2.5 on 2021-07-04 09:24

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'blockquote', 'hr', 'link', 'document-link', 'image'])), ('visualisation', wagtail.core.blocks.StructBlock([('visualisation', wagtail.core.blocks.ChoiceBlock(choices=[('emissions', 'Emissions'), ('temperatures', 'Temperatures')]))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], required=False))])), ('video', wagtail.embeds.blocks.EmbedBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('references', wagtail.core.blocks.RichTextBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text='Use only when all else fails'))]),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'blockquote', 'hr', 'link', 'document-link', 'image'])), ('visualisation', wagtail.core.blocks.StructBlock([('visualisation', wagtail.core.blocks.ChoiceBlock(choices=[('emissions', 'Emissions'), ('temperatures', 'Temperatures')]))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], required=False))])), ('video', wagtail.embeds.blocks.EmbedBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('references', wagtail.core.blocks.RichTextBlock()), ('raw_html', wagtail.core.blocks.RawHTMLBlock(help_text='Use only when all else fails'))]),
        ),
    ]
