# Generated by Django 4.1.5 on 2023-01-26 20:45

from django.db import migrations
import podnebnik.website.models
import wagtail.blocks
import wagtail.contrib.table_block.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_articlelistingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'blockquote', 'hr', 'link', 'document-link', 'image'])), ('visualisation', wagtail.blocks.StructBlock([('visualisation', wagtail.blocks.ChoiceBlock(choices=podnebnik.website.models.VisualisationBlock.get_visualization_choices)), ('caption', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], required=False))])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], required=False))])), ('video', wagtail.embeds.blocks.EmbedBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('references', wagtail.blocks.RichTextBlock()), ('raw_html', wagtail.blocks.RawHTMLBlock(help_text='Use only when all else fails'))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='generalpage',
            name='body',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'italic', 'ol', 'ul', 'blockquote', 'hr', 'link', 'document-link', 'image'])), ('visualisation', wagtail.blocks.StructBlock([('visualisation', wagtail.blocks.ChoiceBlock(choices=podnebnik.website.models.VisualisationBlock.get_visualization_choices)), ('caption', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'document-link'], required=False))])), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], required=False))])), ('video', wagtail.embeds.blocks.EmbedBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('references', wagtail.blocks.RichTextBlock()), ('raw_html', wagtail.blocks.RawHTMLBlock(help_text='Use only when all else fails'))], use_json_field=True),
        ),
    ]
