name: Build website

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yaml'
      - 'assets/**'
      - 'code/**'
      - 'pages/**'
      - 'public/**'
      - 'styles/**'
      - '*config.js'
      - '.config/**'
      - 'package*.json'
      - 'yarn.lock'

  pull_request:
    paths:
      - '.github/workflows/build.yaml'
      - 'assets/**'
      - 'code/**'
      - 'pages/**'
      - 'public/**'
      - 'styles/**'
      - '*config.js'
      - '.config/**'
      - 'package*.json'
      - 'yarn.lock'

  workflow_dispatch:

permissions:
  contents: read # to allow the action to read the repository contents

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install dotnet
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '10.0.x'

      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - run: corepack enable

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          cache: 'yarn'

      - name: Install libvips
        run: sudo apt-get update && sudo apt-get install -y libvips-dev

      - run: yarn install
      - run: yarn build
